"""add logs

Revision ID: 28f692a0d828
Revises: 
Create Date: 2026-01-25 05:15:26.858593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f692a0d828'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scraping_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logs', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scraping_jobs', schema=None) as batch_op:
        batch_op.drop_column('logs')

    # ### end Alembic commands ###
