"""add raw_data and summary

Revision ID: b740e09ef8ac
Revises: 28f692a0d828
Create Date: 2026-01-25 06:08:02.955128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b740e09ef8ac'
down_revision = '28f692a0d828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('raw_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_column('raw_data')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
